site_name: Project Documentation
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true

nav:
  - README: index.md
  - Setup Guide:
    - Frontend & Backend: setup/frontend and backend.md 
    - Pico W: setup/pico.md
    - Docker: setup/docker.md
  - Run: 
    - Run Locally: run/local.md
    - Run with Docker: run/docker.md
  - Test: test.md
  - API Reference:
    - Simulator API:
        - Overview: api/simulator/index.md
        - Endpoints: api/simulator/endpoints.md
        - Examples: api/simulator/examples.md

    - Backend API:
        - Overview: api/backend/index.md
        - Authentication: api/backend/auth.md
        - Desks: api/backend/desks.md
        - Reservations: api/backend/reservations.md
  - Other: other.md

extra_css:
  - assets/styles.css