site_name: Project Documentation
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true

nav:
  - Home: index.md
  - Setup Guide: setup.md
  - Running The Project: run.md
  - API Reference: api.md
  - Other: other.md

extra_css:
  - assets/styles.css